### ISSUE TITLE
Preposition problems

### ISSUE THREAD

**Issue by benshimmin** [donofkarma/express-template#1]
In the `README`, "bored of" should be "bored with" - please fix.

Fowler’s Modern English Usage (rev. 3rd ed.): “The normal constructions are "with" or "by". ... A regrettable tendency has emerged in recent years, esp. in non-standard English in Britain and abroad, to construe the verb with "of".”

**Comment by jasvadgama** [comment]
Can you add a fix and submit a pull request please.

**Comment by benshimmin** [comment]
:-1: No.
